# clippy.toml - MemoryStreamer Clippy Configuration
# Ultra-strict linting for high-performance streaming system
# Targeting 10M+ messages/second and <10Î¼s latency

# =============================================================================
# SUPPORTED THRESHOLD CONFIGURATIONS
# These control the sensitivity of various clippy lints
# =============================================================================

# Core complexity thresholds (widely supported)
cognitive-complexity-threshold = 15
type-complexity-threshold = 200
too-many-arguments-threshold = 8
too-many-lines-threshold = 150

# =============================================================================
# PERFORMANCE NOTES
# =============================================================================

# This configuration prioritizes:
# 1. Safety and correctness (configured via Cargo.toml lints)
# 2. Performance (optimized thresholds above)
# 3. Maintainability (balanced complexity limits)
# 4. Security (strict lints in Cargo.toml)
#
# Lint levels are configured in Cargo.toml [workspace.lints.clippy] section:
# - all = "deny" (maximum strictness)
# - pedantic = "deny" (code quality)
# - nursery = "deny" (experimental but valuable)
# - cargo = "deny" (package quality)
#
# Individual lint overrides are also in Cargo.toml for selective allowances
# where performance or practicality requires flexibility.

# =============================================================================
# ZERO-TOLERANCE QUALITY FRAMEWORK
# =============================================================================

# All thresholds are tuned for:
# - Ultra-high-performance streaming (10M+ messages/second)
# - Sub-10-microsecond latency requirements
# - Zero-tolerance for panics, unwraps, or undefined behavior
# - Mandatory comprehensive testing and documentation
# - Strict formatting and compilation warning elimination